### ISSUE TITLE
Constant MQTT disconnect/reconnect.

### ISSUE THREAD

**Issue by necoras** [OpenZWave/Zwave2Mqtt#44]
I'm seeing a constant disconnect/reconnecting of the MQTT client. I'm running a mosquitto client on the same Raspberry pi that zwave2mqtt and HA are running on. My zwave2mqtt logs are filled with this:

2019-06-28T04:42:10.379Z z2m:Mqtt MQTT client reconnecting
2019-06-28T04:42:10.384Z z2m:Mqtt MQTT client closed
2019-06-28T04:42:15.389Z z2m:Mqtt MQTT client reconnecting
2019-06-28T04:42:15.393Z z2m:Mqtt MQTT client closed
2019-06-28T04:42:20.395Z z2m:Mqtt MQTT client reconnecting
2019-06-28T04:42:20.400Z z2m:Mqtt MQTT client closed

I'm fairly certain that the gateway isn't talking to the MQTT broker at all either. My zwave devices don't respond to injected messages, and the gateway doesn't seem to send out any messages when I trigger the devices. Is this a misconfiguration on my end, or a problem with the code? The auth details are correct, as are the URL and Port.

**Comment by robertsLando** [comment]
Sorry this was a problem with latest version, should be fixed by latest commit ea79b21d2ccfc57edfd68c1f57d9f7c0fdfdebe7

Please let me know if now works as expected and close the issue if it is ok

**Comment by necoras** [comment]
Good to hear it's likely fixed. I'm pulling from the Hass.io Add-ons store, so once the change is pushed there I'll test and respond here. Thanks!

**Comment by seletz** [comment]
I've rebuilt the docker image locally and it seems the bug is still there.  This is on an arm based device (a revpi core).  I confirmed that I can reach the MQTT broker from the device using mosquitto_sub.

```
2019-07-02T08:36:53.444Z z2m:Store scenes.json not found
2019-07-02T08:36:54.212Z z2m:App Application path:/usr/src/app
Initialising OpenZWave 1.4.1 binary addon for Node.JS.
        OpenZWave Security API is ENABLED
        ZWave device db    : /usr/local/etc/openzwave/
        User settings path : /usr/src/app/store
        Option Overrides : --Logging undefined --ConsoleOutput undefined --QueueLogLevel 6 --DriverMaxAttempts 9999 --SaveConfiguration true --PollInterval 1000
2019-07-02T08:36:54.384Z z2m:Zwave Connecting to /dev/ttyACM0
2019-07-02 08:36:54.387 Always, OpenZwave Version 1.4.1 Starting Up
2019-07-02 08:36:54.387 Warning, Failed - Network Key Not Set
2019-07-02T08:36:54.553Z z2m:App Listening on port 8091
2019-07-02 08:36:54.579 Warning, CheckCompletedNodeQueries m_allNodesQueried=0 m_awakeNodesQueried=0
2019-07-02 08:36:54.579 Warning, CheckCompletedNodeQueries all=1, deadFound=0 sleepingOnly=1
2019-07-02T08:36:54.718Z z2m:Zwave Scanning network with homeid: 0xe8f8b857
2019-07-02T08:36:54.720Z z2m:Zwave Node added 1
2019-07-02T08:36:54.722Z z2m:Zwave node 1 AVAILABLE: Z-Wave.Me - ZME_UZB1 USB Stick (Static PC Controller)
2019-07-02T08:36:54.724Z z2m:Zwave ValueAdded: 1-32-1-0 Basic
2019-07-02T08:36:54.729Z z2m:Zwave node 1 ready: Z-Wave.Me - ZME_UZB1 USB Stick (Static PC Controller)
2019-07-02T08:36:54.731Z z2m:Zwave Network scan complete. Found: 1 nodes
2019-07-02T08:36:54.746Z z2m:Mqtt MQTT client offline
2019-07-02T08:36:54.750Z z2m:Mqtt MQTT client closed
2019-07-02T08:36:58.747Z z2m:App New connection eRhyM8rB9JWZxswGAAAA
2019-07-02T08:36:59.750Z z2m:Mqtt MQTT client reconnecting
2019-07-02T08:36:59.759Z z2m:Mqtt MQTT client closed
2019-07-02T08:37:04.759Z z2m:Mqtt MQTT client reconnecting
2019-07-02T08:37:04.764Z z2m:Mqtt MQTT client closed
2019-07-02T08:37:09.764Z z2m:Mqtt MQTT client reconnecting
2019-07-02T08:37:09.768Z z2m:Mqtt MQTT client closed

```

**Comment by seletz** [comment]
For reference -- the docker image references this commit: 2adc2dd6eebcfa292817fada90afa115a240ab1e

**Comment by robertsLando** [comment]
You should refer to this commit: 
https://github.com/OpenZWave/Zwave2Mqtt/commit/8c112ac6b30781656fa8739894a77fbc8a177338

Daniel

**Comment by seletz** [comment]
Hrmpf.  I actually double-checked.  -ENOCOFFEE probably.  Will check again and report back.

**Comment by robertsLando** [comment]
@seletz  What does ENOCOFFEE means?
