### ISSUE TITLE
Adding Fibaro FGSS101 Smoke Sensor crashes Container

### ISSUE THREAD

**Issue by wzbfyb** [OpenZWave/Zwave2Mqtt#565]
3.7 docker compose

Build/Run method
- [ x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.2.2
Openzwave Version: 1.6.1133

**Describe the bug**
Adding the Fibaro smoke alarm to zwave2mqtt crashes the container

**To Reproduce**
1. Go to 'control panel'
2. Click on 'add node'
3. tripple click the B button on the smoke sensor

```
zwave2mqtt    |   z2m:App Zwave api call: addNode [ true ] +3m
zwave2mqtt    |   z2m:Zwave Success zwave api call startInclusion  +3m
zwave2mqtt    |   z2m:Zwave controller command { nodeid: 0, state: 1, errcode: 0, help: 'AddDevice Starting' } +4ms
zwave2mqtt    |   z2m:Zwave controller command { nodeid: 0, state: 4, errcode: 0, help: 'AddDevice Waiting' } +3ms
zwave2mqtt    |   z2m:Zwave controller command { nodeid: 0, state: 6, errcode: 0, help: 'AddDevice InProgress' } +21s
zwave2mqtt    |   z2m:Zwave controller command { nodeid: 8, state: 6, errcode: 0, help: 'AddDevice InProgress' } +196ms
zwave2mqtt    |   z2m:Zwave controller command { nodeid: 8, state: 6, errcode: 0, help: 'AddDevice InProgress' } +770ms
zwave2mqtt    |   z2m:Zwave Node added 8 +55ms
zwave2mqtt    |   z2m:Zwave controller command { nodeid: 8, state: 7, errcode: 0, help: 'AddDevice Completed' } +3ms
zwave2mqtt    |   z2m:Zwave Notification from node 8: Notification - NoOperation (2) +30ms
zwave2mqtt    | 2020-06-09 07:36:56.781 Warning, Node008, CommandClass Version is 0, Removing CommandClass COMMAND_CLASS_NOTIFICATION
zwave2mqtt    |   z2m:Zwave ValueAdded: 8-112-1-1 Smoke alarm cancellation delay +271ms
zwave2mqtt    |   z2m:Zwave ValueAdded: 8-112-1-2 LED indicator and acoustic alarm turned ON / OFF at any alarm type +8ms
zwave2mqtt    |   z2m:Zwave ValueAdded: 8-112-1-5 Type of alarm frame for association group 1 +7ms
zwave2mqtt    |   z2m:Zwave ValueAdded: 8-112-1-7 Forced Level of Dimming group 1 +7ms
zwave2mqtt    |   z2m:Zwave ValueAdded: 8-112-1-10 Temperature report interval +6ms
zwave2mqtt    |   z2m:Zwave ValueAdded: 8-112-1-12 Temperature report hysteresis +7ms
zwave2mqtt    |   z2m:Zwave ValueAdded: 8-112-1-13 Alarm broadcast +6ms
zwave2mqtt    |   z2m:Zwave ValueAdded: 8-112-1-73 Temperature measurement compensation +5ms
zwave2mqtt    |   z2m:Zwave ValueAdded: 8-112-1-80 Z-Wave range test interval +4ms
zwave2mqtt    |   z2m:Zwave ValueAdded: 8-112-1-81 Temperature alarm threshold +4ms
zwave2mqtt    |   z2m:Zwave ValueAdded: 8-112-1-82 Smoke Sensor sensitivity +4ms
zwave2mqtt    | 2020-06-09 07:36:56.973 Warning, Node008, CommandClass Version is 0, Removing CommandClass COMMAND_CLASS_NOTIFICATION
zwave2mqtt    |   z2m:Zwave ValueAdded: 8-112-1-83 Black Box sensitivity level +4ms
zwave2mqtt    |   z2m:Zwave ValueAdded: 8-112-1-84 Malfunction alarm +5ms
zwave2mqtt    |   z2m:Zwave ValueAdded: 8-112-1-85 Temperature alarm +5ms
zwave2mqtt    |   z2m:Zwave ValueAdded: 8-112-1-86 Lack of the Z-Wave range alarm +4ms
zwave2mqtt    |   z2m:Zwave ValueAdded: 8-112-1-87 Low battery alarm +4ms
zwave2mqtt    |   z2m:Zwave ValueAdded: 8-112-1-88 Consider temperature measurement compensation +4ms
zwave2mqtt    |   z2m:Zwave ValueAdded: 8-112-1-89 Tamper alarm +5ms
zwave2mqtt    |   z2m:Zwave node 8 AVAILABLE: FIBARO System - FGSS101 Smoke Sensor (Routing Alarm Sensor) +9ms
zwave2mqtt    | 2020-06-09 07:36:57.010 Warning, Node008, Node::GetValue - Couldn't find ValueID in Store: HomeID: 0xef52197f, ValueID: (Id 0x02020000089c4013, NodeID 8, Genre config, CC 0x71, Instance 1, Index 514, Type int)
zwave2mqtt    | 2020-06-09 07:36:57.010 Warning, Exception: Manager.cpp:1570 - 101 - Invalid ValueID passed to GetValueLabel
zwave2mqtt    | terminate called after throwing an instance of 'OpenZWave::OZWException'
zwave2mqtt    |   what():  Manager.cpp:1570 - InvalidValueIDError (101) Msg: Invalid ValueID passed to GetValueLabel
pi@raspberrypi:~ $ 
```

**Expected behavior**
that the node is added, like my Heiman sensors

**Comment by robertsLando** [comment]
Problem should be fixed in openzwave-shared@1.7.1

**Comment by wzbfyb** [comment]
Well, it still does not work @robertsLando 

`  z2m:App Zwave api call: addNode [ true ] +3m
  z2m:Zwave Success zwave api call startInclusion  +25s
  z2m:Zwave controller command { nodeid: 0, state: 1, errcode: 0, help: 'AddDevice Starting' } +3ms
  z2m:Zwave controller command { nodeid: 0, state: 4, errcode: 0, help: 'AddDevice Waiting' } +3ms
  z2m:Zwave controller command { nodeid: 0, state: 6, errcode: 0, help: 'AddDevice InProgress' } +12s
  z2m:Zwave controller command { nodeid: 9, state: 6, errcode: 0, help: 'AddDevice InProgress' } +4ms
  z2m:Zwave controller command { nodeid: 9, state: 6, errcode: 0, help: 'AddDevice InProgress' } +437ms
  z2m:Zwave Node added 9 +62ms
  z2m:Zwave controller command { nodeid: 9, state: 7, errcode: 0, help: 'AddDevice Completed' } +4ms
  z2m:Zwave Notification from node 9: Notification - NoOperation (2) +30ms
2020-06-17 10:51:38.692 Warning, Node009, CommandClass Version is 0, Removing CommandClass COMMAND_CLASS_NOTIFICATION
  z2m:Zwave ValueAdded: 9-112-1-1 Smoke alarm cancellation delay +245ms
  z2m:Zwave ValueAdded: 9-112-1-2 LED indicator and acoustic alarm turned ON / OFF at any alarm type +9ms
  z2m:Zwave ValueAdded: 9-112-1-5 Type of alarm frame for association group 1 +9ms
  z2m:Zwave ValueAdded: 9-112-1-7 Forced Level of Dimming group 1 +11ms
  z2m:Zwave ValueAdded: 9-112-1-10 Temperature report interval +5ms
  z2m:Zwave ValueAdded: 9-112-1-12 Temperature report hysteresis +4ms
  z2m:Zwave ValueAdded: 9-112-1-13 Alarm broadcast +5ms
  z2m:Zwave ValueAdded: 9-112-1-73 Temperature measurement compensation +4ms
  z2m:Zwave ValueAdded: 9-112-1-80 Z-Wave range test interval +5ms
2020-06-17 10:51:38.880 Warning, Node009, CommandClass Version is 0, Removing CommandClass COMMAND_CLASS_NOTIFICATION
  z2m:Zwave ValueAdded: 9-112-1-81 Temperature alarm threshold +4ms
  z2m:Zwave ValueAdded: 9-112-1-82 Smoke Sensor sensitivity +6ms
  z2m:Zwave ValueAdded: 9-112-1-83 Black Box sensitivity level +4ms
  z2m:Zwave ValueAdded: 9-112-1-84 Malfunction alarm +5ms
  z2m:Zwave ValueAdded: 9-112-1-85 Temperature alarm +4ms
  z2m:Zwave ValueAdded: 9-112-1-86 Lack of the Z-Wave range alarm +4ms
  z2m:Zwave ValueAdded: 9-112-1-87 Low battery alarm +5ms
  z2m:Zwave ValueAdded: 9-112-1-88 Consider temperature measurement compensation +4ms
  z2m:Zwave ValueAdded: 9-112-1-89 Tamper alarm +5ms
  z2m:Zwave node 9 AVAILABLE: FIBARO System - FGSS101 Smoke Sensor (Routing Alarm Sensor) +5ms
2020-06-17 10:51:38.924 Warning, Node009, Node::GetValue - Couldn't find ValueID in Store: HomeID: 0xef52197f, ValueID: (Id 0x02020000099c4013, NodeID 9, Genre config, CC 0x71, Instance 1, Index 514, Type int)
2020-06-17 10:51:38.928 Warning, Exception: Manager.cpp:1570 - 101 - Invalid ValueID passed to GetValueLabel
2020-06-17 10:51:38.931 Warning, Node009, Node::GetValue - Couldn't find ValueID in Store: HomeID: 0xef52197f, ValueID: (Id 0x02020000099c4013, NodeID 9, Genre config, CC 0x71, Instance 1, Index 514, Type int)
2020-06-17 10:51:38.931 Warning, Exception: Manager.cpp:1626 - 101 - Invalid ValueID passed to GetValueUnits
2020-06-17 10:51:38.932 Warning, Node009, Node::GetValue - Couldn't find ValueID in Store: HomeID: 0xef52197f, ValueID: (Id 0x02020000099c4013, NodeID 9, Genre config, CC 0x71, Instance 1, Index 514, Type int)
2020-06-17 10:51:38.932 Warning, Exception: Manager.cpp:1686 - 101 - Invalid ValueID passed to GetValueHelp
2020-06-17 10:51:38.933 Warning, Node009, Node::GetValue - Couldn't find ValueID in Store: HomeID: 0xef52197f, ValueID: (Id 0x02020000099c4013, NodeID 9, Genre config, CC 0x71, Instance 1, Index 514, Type int)
2020-06-17 10:51:38.933 Warning, Exception: Manager.cpp:1789 - 101 - Invalid ValueID passed to IsValueReadOnly
2020-06-17 10:51:38.933 Warning, Node009, Node::GetValue - Couldn't find ValueID in Store: HomeID: 0xef52197f, ValueID: (Id 0x02020000099c4013, NodeID 9, Genre config, CC 0x71, Instance 1, Index 514, Type int)
2020-06-17 10:51:38.933 Warning, Exception: Manager.cpp:1813 - 101 - Invalid ValueID passed to IsValueWriteOnly
2020-06-17 10:51:38.934 Warning, Node009, Node::GetValue - Couldn't find ValueID in Store: HomeID: 0xef52197f, ValueID: (Id 0x02020000099c4013, NodeID 9, Genre config, CC 0x71, Instance 1, Index 514, Type int)
2020-06-17 10:51:38.934 Warning, Exception: Manager.cpp:1741 - 101 - Invalid ValueID passed to GetValueMin
2020-06-17 10:51:38.934 Warning, Node009, Node::GetValue - Couldn't find ValueID in Store: HomeID: 0xef52197f, ValueID: (Id 0x02020000099c4013, NodeID 9, Genre config, CC 0x71, Instance 1, Index 514, Type int)
2020-06-17 10:51:38.934 Warning, Exception: Manager.cpp:1765 - 101 - Invalid ValueID passed to GetValueMax
2020-06-17 10:51:38.934 Warning, Node009, Node::GetValue - Couldn't find ValueID in Store: HomeID: 0xef52197f, ValueID: (Id 0x02020000099c4013, NodeID 9, Genre config, CC 0x71, Instance 1, Index 514, Type int)
2020-06-17 10:51:38.934 Warning, Exception: Manager.cpp:1861 - 101 - Invalid ValueID passed to IsValuePolled
2020-06-17 10:51:38.935 Warning, Node009, Node::GetValue - Couldn't find ValueID in Store: HomeID: 0xef52197f, ValueID: (Id 0x02020000099c4013, NodeID 9, Genre config, CC 0x71, Instance 1, Index 514, Type int)
2020-06-17 10:51:38.935 Warning, Exception: Manager.cpp:2071 - 101 - Invalid ValueID passed to GetValueAsInt
undefined:0



[Error: Exception calling OpenZWave::Manager::GetValueAsInt in /openzwave/cpp/src/Manager.cpp(2071): Invalid ValueID passed to GetValueAsInt]
`

**Comment by wzbfyb** [comment]
It is a different error message by now. BTW this is zwave2mqtt 3.3.0
